config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/about'

  get 'pages/offerings'

  get 'pages/public_speaking'

  root to: "pages#home"
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do 
     resource :profile
  end 
  get 'about', to: 'pages#about'
  resources :contacts, only: [:create]
  get 'contact-us', to: 'contacts#new', as: 'new_contact' 
  get 'offerings', to: 'pages#offerings'
  get 'business_writing', to: 'pages#business_writing'
  get 'nonverbal', to: 'pages#nonverbal'
  get 'group_dynamics', to: 'pages#group_dynamics'
  get 'intercultural_communication', to: 'pages#intercultural_communication'
  get 'editing', to: 'pages#editing'
  get 'interviewing', to: 'pages#interviewing'
  get 'business_etiquette', to: 'pages#business_etiquette'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # Contact Form Validations.
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan <ActiveRecord::Base
    has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  # If Pro user passes validations (email, password, etc)
  # the ncall Stripe and tell Stripe to set up a subscription upon
  # charging the customer's card.
  # Stripe responds back with customer data.
  # Store customer.id as the customer token and save the user. 
  def save_with_subscription
    if valid?
    customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
    self.stripe_customer_token = customer.id
    save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # Whitelist the following form fields so that we can process them, if coming
  # from a Devise sign up form
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up){ |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation)}
  end 
end

app/controllers/contacts_controller.rb
class ContactsController <ApplicationController
    def new
    @contact =Contact.new
    end
    
    def create
    @contact = Contact.new(contact_params)
    if @contact.save
        name = params[:contact][:name]
        email = params[:contact][:email]
        body = params[:contact][:comments]
      ContactMailer.contact_email(name, email, body).deliver
        flash[:success] = "Message sent."
        redirect_to new_contact_path
    else 
        flash[:danger] = @contact.errors.full_messages.join(",")
        redirect_to new_contact_path
    end
    
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)
        end
end 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def offerings
  end

  def public_speaking
  end
  
  def nonverbal
  end 
  
  def business_writing
  end 
  
  def group_dynamics
  end 
  
  def intercultural_communication
  end 
  
  def editing
  end 
  
  def interviewing
  end 
  
  def business_etiquette
  end 

end 

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  
  # GET to /users/:user_id/profile/new
  def new
   # Render blank profile details form
   @profile = Profile.new
  end 
  
  # POST /users/:user_id/profile
  def create
    # Ensure that we have the user who is filling out the form
    @user= User.find( params[:user_id] )
    # Create profile linked to this specific user
    @profile = @user.build_profile( profile_params )
    if @profile.save
      flash[:success] = "Profile Updated"
        redirect_to user_path(id: params[:user_id] )
    else 
      render action :new
    end
  end 
  
  # GET to /users/:user_id/profile/edit
  def edit
    @user = User.find( params[:user_id])
    @profile = @user.profile
  end
  
  # PUT or PATCH to /users/:user_id/profile
  def update
    # Retrieve the user from the databse
    @user = User.find( params[:user_id])
    # Retrieve that user's profile
    @profile = @user.profile
    # Mass assign edited profile attributes and save (update)
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile Updated!"
      # Redirect user to their profile page
      redirect_to user_path(id: params[:user_id])
    else 
      render action :edit
    end
  end 
  
  private 
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
    end 
    
    def only_current_user
     @user = User.find( params[:user_id] )
     redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new
  
  # Extend default Devise gem behavior so that 
  # users signing up with the Pro account (plan ID 2)
  # save with a special Stripe subsription function.
  # Otherwise Devise signs up user as usual.
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
  
  private
  def select_plan
    unless (params[:plan] == '1' || params[:plan] == '2')
    flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @users = User.includes(:profile) 
  end 
  
  # GET to users/:id 
  def show
    @user = User.find( params[:id])
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def job_title_icon
    if @user.profile.job_title == "Developer"
      "<i class='fa fa-code'></i>".html_safe
    elsif @user.profile.job_title == "Entrepreneur"
    "<i class='fa fa-lightbulb-o'></i>".html_safe
    elsif @user.profile.job_title == "Investor"
    "<i class='fa fa-dollar'></i>".html_safe
    end 
  end  
end 

app/views/contacts/new.html.erb
<div class="container">
    <div class="row">
        <h3 class="header-contact"> Contact Us </h3>
        <h4 class="subheading-contact"> Have any questions? Shoot us an e-mail!</h4>
        <div class="col-md-4 col-md-offset-4">
            <div class="well">
            <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%=f.text_field :name , class: 'form-control' %>
                </div>
                <div class="form-group">
                     <%= f.label :email %>
                    <%=f.text_field :email , class: 'form-control' %>
                </div>
                <div class="form-group">
                     <%= f.label :comments %>
                     <%=f.text_area :comments, class: 'form-control' %>
                </div>
                <%= f.submit 'Submit', class: 'btn btn-default' %>
                <% end %>
            </div>
          </div>       
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    
 <nav class="navbar navbar-default navbar-static-top" role="navigation">
   
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
     <%= link_to root_path, class: "navbar-brand" do %>
       <i class="fa fa-group"></i>
       C. R. Communication Strategies
      <% end %>
      
    </div>
  
  <div class="navbar-order">
    <ul class="nav navbar-nav navbar-right">
      <div class="dropdown">
        <button class="dropbtn"><li><%= link_to "Offerings", offerings_path %></li></button>
        
        <div class="dropdown-content">
          <li><%= link_to "Public Speaking", pages_public_speaking_path %></li>
          <li><%= link_to "Nonverbal Communication", nonverbal_path %></li>
          <li><%= link_to "Group Dynamics", group_dynamics_path %></li>
          <li><%= link_to "Intercultural Communication", intercultural_communication_path %></li>
          <li><%= link_to "Editing", editing_path %></li>
          <li><%= link_to "Interviewing", interviewing_path %></li>
          <li><%= link_to "Business Etiquette", business_etiquette_path %></li>
          <li><%= link_to "Business Writing", business_writing_path %></li>
        </div>
      </div>
     

     <li><%= link_to "About", about_path %></li>
     <li><%= link_to "Contact Form", new_contact_path %></li>
    
     </ul>
   </div>
      
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

  <div class="container flash-container">
    <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{type}" %>
    <% end %>  
  </div>    
  

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
     <div class="row-fluid">
         <div class="container text-center-about">
              <h1 class="header-about"> About Me </h1>
         </div>
      </div> 
    </div>
</div>

<div class="container home-signup-links">
  <div class="row">
    <div class="about-image-container">
      <img class="about-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/About+page-+Headshot+of+Mom.jpg">
    </div>
      <p class="about-text">
        <p class="qualifications">My experience includes 14 years as a business communication college
        instructor, speaker, and consultant, specializing in topics from presentation
        skills to business writing to nonverbal communication.
        
        <h2 class="subheading-about">My Qualifications</h2>
          <li class="qualifications">B.A. in Communication Studies from Indiana University Purdue 
          University Indianpolis, member of the debate team.</li>
          <li class="qualifications">Master's degree in Organizational Management from Pfeiffer University
          in Charlotte, NC</li>
        </p>
  
        <h2 class="subheading-about">Client List</h2>
          <li class="client">Belmont Abbey College</li>
          <li class="client">Central Piedmont Community College</li>
          <li class="client">Allstate Insurance</li>
          <li class="client">Christ The King Catholic High School</li>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/business_etiquette.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header"> Business Etiquette</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>
  
<div class="row">
  <div class="workshop-image"><img class="workshop-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Business+Etiquette.jpg">
</div>

<div class="row">
  <p class="course-summary">This is the business etiquette page.</p>
</div>

<div class="row">
  <p class="course-summary">This public speaking class will prepare you on how to speak <strong>confidently</strong> in front of a group.</p>
</div>

app/views/pages/business_writing.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header"> Business Writing</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>

<center>
  <div class="row">
    <div class="workshop-image"><img class="workshop-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Business+Writing.jpg">
  </div>
  
  <div class="row">
    <p class="course-summary">This course will teach participants to write audience-centered, 
    clear, and concise messages using typical business formats. Particular focus on the writing process, 
    organization, and editng to produce routine, negative, and persuasive business messages.</p>
  </div>
  
  <div class="row">
      <h2 class="course-topic"><strong>You Will Learn About:</strong></h2>
  </div>
  
  <div class="row">
    <h4 class="course-subtopic">
      <ol class="course-list">
         <li>Business Message Planning </li>
         <li>Business Message Writing </li>
         <li>Edit and Proofreading </li>
         <li>Format Tips</li>
         <li>Content Strategies</li>
         <li>Routine Messages</li>
         <li>Negative Messages</li>
         <li>Persuasive Messages</li>
      </ol>
    </h4>
  </div>
  
  <div class="course-summary">
    <p>Interesting in increasing your business writing skills to communicate professional messages in a clear and understanable way? Contact Us.</p>
  </div>
  
  
  </center>
</div>

app/views/pages/editing.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header"> Editing</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>
  
<div class="row">
  <div class="workshop-image"><img class="workshop-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-++Editing.jpg">
</div>
  
  <div class="row">
  <p class="course-summary">This is the editing page.</p>
</div>

<div class="row">
  <p class="course-summary">This public speaking class will prepare you on how to speak <strong>confidently</strong> in front of a group.</p>
</div>

app/views/pages/group_dynamics.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header">Group Dynamics</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>

<div class="row">
  <div class="workshop-image"><img class="workshop-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Group+Dynamics.jpg">
</div>

<div class="row">
  <p class="course-summary">This is the group dynamics page.</p>
</div>

<div class="row">
  <p class="course-summary">This public speaking class will prepare you on how to speak <strong>confidently</strong> in front of a group.</p>
</div>

app/views/pages/home.html.erb
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">


   <div class="container home-signup-links">
      <div class="row">
        <div class="header-box">
          <h1 class="text-upper"> <img src="https://crcommunications.s3.us-east-2.amazonaws.com/Home+page-+oval+handing+portfolio+over.jpg";> Business communication training</h1>  
        </div>
           <p class="paragraph-upper"> Hone your business writing and presentation skills.</p>
      </div>
    </div>
    
      <div class="button">
          <%= link_to "Explore Our Offerings", offerings_url, class: 'btn btn-primary btn-lg btn-block' %>
          
            <p>  </p>
    </div>


        
    <div class="container lower-page">
       <div class="col-md-3">
            <a href="<%= pages_public_speaking_path %>"><h1 class="lower-heading"> Public Speaking</h1></a>
            <p class="lower-paragraph">80% of what you say is through your body language.</p>
        </div>
        
      <div class="row lower-page-content">
        <div class="col-md-3">
             <a href="<%= business_writing_path %>"><h1 class="lower-heading"> Business Writing</h1></a>
            <p class="lower-paragraph"> Learn the do's and don'ts of communicating.</p>
        </div>
    
        <div class="col-md-3">
          <a href="<%= group_dynamics_path %>"><h1 class="lower-heading"> Group Dynamics</h1></a>
          <p class="lower-paragraph">90% of employers indicate they want their employees to demonstrate group competency.</p>
        </div>
        
         <div class="col-md-3">
          <a href="<%= editing_path %>"><h1 class="lower-heading"> Editing</h1></a>
          <p class="lower-paragraph">Avoid proofreading mistakes to come across more credible.</p>
        </div>
      </div>
    
    </div>

app/views/pages/intercultural_communication.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header"> Intercultural Communication</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>

<div class="row">
  <div class="workshop-image"><img class="workshop-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Intercultural+Comm.jpg">
</div>
  
<div class="row">
  <p class="course-summary">This is the intercultural communication page.</p>
</div>

<div class="row">
  <p class="course-summary">This public speaking class will prepare you on how to speak <strong>confidently</strong> in front of a group.</p>
</div>

app/views/pages/interviewing.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header"> Interviewing</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>
  
<div class="row">
  <div class="workshop-image"><img class="workshop-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Interviewing.jpg">
</div>
  
<div class="row">
  <p class="course-summary">This is the interviewing page.</p>
</div>

<div class="row">
  <p class="course-summary">This public speaking class will prepare you on how to speak <strong>confidently</strong> in front of a group.</p>
</div>

app/views/pages/nonverbal.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header"> Nonverbal Communication</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>

<div class="row">
  <div class="workshop-image"><img class="workshop-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Nonverbal+Communication.jpg">
</div>
  
<div class="row">
  <p class="course-summary">This is the nonverbal communication page.</p>
</div>

<div class="row">
  <p class="course-summary">This public speaking class will prepare you on how to speak <strong>confidently</strong> in front of a group.</p>
</div>

app/views/pages/offerings.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header"> Workshop Offerings</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>

<div class="container home-signup-links">
  <div class="row">
    <p class="top-paragraph">
      C. R. Communications offers several instructional workshops to build business writing and presentation skills.
    </p>
  
  <div class="row">
    <div class="col-md-4">
      <a href="<%= pages_public_speaking_path %>"><div class="course-image"><img class="course-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Public+Speaking.jpg"></a>
      </div>
    </div>
  
   <div class="col-md-4">
     <a href="<%= nonverbal_path %>"><div class="course-image"><img class="course-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Nonverbal+Communication.jpg"></a>
     </div>
    </div>
  
   <div class="col-md-4">
      <a href="<%= group_dynamics_path %>"><div class="course-image"><img class="course-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Group+Dynamics.jpg"></a>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-4">
     <a href="<%= pages_public_speaking_path %>"><h1 class="blue-header">Public Speaking </h1></a>
      
      <h3 class="offerings-info">Learn proper techniques for speaking in front of an audience. Body language is key.</h3>
    </div>
      
    <div class="col-md-4">
      <a href="<%= nonverbal_path %>"><h1 class="blue-header">Nonverbal Communication </h1></a>
      <h3 class="offerings-info">What you don't say says a lot about you. Watch your gestures.</h3>
    </div>
  
   <div class="col-md-4">
     <a href="<%= group_dynamics_path %>"><h1 class="blue-header">Group Dynamics </h1></a>
      <h3 class="offerings-info">90% of employers indicate they want their employees to demonstrate group competency.</h3>
   </div>
  </div>
      
  <div class="row">
    <div class="col-md-4">
      <a href="<%= intercultural_communication_path %>"><div class="course-image"><img class="course-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Intercultural+Comm.jpg"></a>
      </div>
    </div>
  
   <div class="col-md-4">
      <a href="<%= editing_path %>"><div class="course-image"><img class="course-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-++Editing.jpg"></a>
     </div>
   </div>
  
   <div class="col-md-4">
        <a href="<%= interviewing_path %>"><div class="course-image"><img class="course-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Interviewing.jpg"></a>
      </div>
   </div>
  </div>
  
  <div class="row">
    <div class="col-md-4">
      <a href="<%= intercultural_communication_path %>"><h1 class="blue-header">Intercultural Communication </h1></a>
      <h3 class="offerings-info">Intercultural Communication is a discipline that studies communication 
      across different cultures and social groups, or how culture affects communication.</h3>
    </div>
      
    <div class="col-md-4">
      <a href="<%= editing_path %>"><h1 class="blue-header">Editing </h1></a>
      <h3 class="offerings-info">Avoid proofreading mistakes to come across more credible.</h3>
    </div>
  
    <div class="col-md-4">
     <a href="<%= interviewing_path %>"><h1 class="blue-header">Interviewing </h1></a>
      <h3 class="offerings-info">Learn what to ask and what not to ask while interviewing.</h3>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-4">
      <a href="<%= business_etiquette_path %>"><div class="course-image"><img class="course-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Business+Etiquette.jpg"></a>
      </div>
    </div>
  
    <div class="col-md-4">
      <a href="<%= business_writing_path %>"><div class="course-image"><img class="course-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Business+Writing.jpg"></a>
      </div>
    </div>
  </div>
  
  <div class="row">
   <div class="col-md-4">
       <a href="<%= business_etiquette_path %>"><h1 class="blue-header">Business Etiquette </h1></a>
      <h3 class="offerings-info">How you should act while on lunch with your boss.</h3>
   </div>
    
   <div class="col-md-4">
       <a href="<%= business_writing_path %>"><h1 class="blue-header">Business Writing </h1></a>
       <h3 class="offerings-info">Active, not passive voice, etc.</h3>
   </div>
 </div>
</div>

app/views/pages/public_speaking.html.erb
<div class="container">
  <div class="row">
    <div class="row-fluid">
     <div class="container text-center">
       <h1 class="header"> Public Speaking</h1>
         <hr>
     </div>
    </div> 
  </div>
</div>

<div class="row">
  <div class="workshop-image"><img class="workshop-image" img src="https://crcommunications.s3.us-east-2.amazonaws.com/Offerings-+Public+Speaking.jpg"></a>
  </div>
</div>

<div class="row">
  <p class="course-summary">This is the public speaking page.</p>
</div>

<div class="row">
  <p class="course-summary">This public speaking class will prepare you on how to speak <strong>confidently</strong> in front of a group.</p>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Edit Your Profile</h1>
      <p class="text-center"> Be a part of the DevMatch community and fill out your profile!</p>
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1 class="text-center">Create Your Profile</h1>
      <p class="text-center"> Be a part of the DevMatch community and fill out your profile!</p>
      <div class="well">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h1 class="text-center">DevMatch Community</h1>
          <p class="text-center">Welcome ot the DevMatch Community. Users must fill out a profile in order to be visible in the community. </p>
      <ul class="list-unstyled">
        <% @users.each do |user| %>
        <% if user.profile %>
          <li>
            <div class="well row <%= cycle('white-bg', '')%>">
              <div class="col-sm-4 text-center">
                <% if user.profile.avatar %>
                  <%= link_to user do %>
                    <%= image_tag user.profile.avatar.url, class: 'user-index-avatar' %>
                 <% end %>
                <% end %> 
              </div>
              <div>
                <%= link_to user do %>
                  <h2><%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                <% end %> 
                <p>
                  <%= user.profile.job_title %>
                  <% if user.plan_id ==2 %>
                    <span class="label label-danger">PRO</span>
                  <% end %>
               </p>
                
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 text-center">
      <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img' %>
    </div>
    
    <div class="col-md-6">
      <h1><%= @user.profile.first_name %>  <%= @user.profile.last_name %></h1> 
      <h3><span class="job-title-icon"><%= job_title_icon %></span><%= @user.profile.job_title %></h3>
      <div class="well profile-block profile-description">
        <h3>Description</h3>
       <%= @user.profile.description %>
      </div>
      <% if current_user.plan_id ==2 %>
      <div class="well profile-block profile-contact-info">
        <h3>Contact Information</h3>
        <%= @user.profile.phone_number %></br>
        <%= @user.profile.contact_email %></br>
      <% end %>
      </div>
   </div>
  </div>
</div>